<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE questions[
    <!ELEMENT questions (question*)>
    <!ELEMENT question (type, title, option*, answer+)>
    <!ATTLIST question
    id CDATA #REQUIRED>
    <!ELEMENT type (#PCDATA)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT option (#PCDATA)>
    <!ELEMENT answer (#PCDATA)>
]>
<questions>
    <question id="1">
        <type>radio</type>
        <title>1. ¿En qué año gano España su primer Mundial de Futbol?</title>
        <option>1985</option>
        <option>1927</option>
        <option>2010</option>
        <option>Ninguna de las anteriores </option>
        <answer>2</answer>
    </question>
    <question id="2">
        <type>text</type>
        <title>2. Si tu conduces un autobus con 40 pasajeros y en la siguiente parada se bajan 13 pasajeros, ¿Quien conduce el autobus?</title>
        <answer>Yo</answer>
    </question>
    <question id="3">
        <type>checkbox</type>
        <title>3. Doscientos patos metidos en un cajón,¿cuantas patas y picos son?</title>
        <option>2 picos y 4 patas</option>
        <option>200 picos y 400 patas</option>
        <option>Patata</option>
        <option>Ninguna de las anteriores</option>
        <answer>0</answer>
    </question>
    <question id="4">
        <type>select</type>
        <title>4. ¿Que habilidad utiliza Naruto?</title>
        <option>Rasengan</option>
        <option>Raikiri</option>
        <option>Chidori</option>
        <option>Pistola Agua</option> 
        <answer>0</answer>
    </question>
    <question id="5">
        <type>multiple</type>
        <title>5. ¿Quien de los siguentes jugadores juega o ha jugado en el Real Madrid?</title>
        <option>Zidane</option>
        <option>Michael Jordan</option>
        <option>Godin</option>
        <option>Lewandowski</option>
        <option>Marco Asensio</option>
        <answer>0</answer>
        <answer>4</answer>
    </question>
    <question id="6">
        <type>radio</type>
        <title>6. Selecciona la palabra correcta:</title>
        <option>Havía</option>
        <option>Abía</option>
        <option>Había</option>
        <option>Avía</option>
        <answer>2</answer>
    </question>
    <question id="7">
        <type>text</type>
        <title>7. ¿En qué mes una niña habladora habla menos?</title>
        <answer>En febrero</answer>
    </question>
    <question id="8">
        <type>checkbox</type>
        <title>8. ¿Cuántos meses tienen 28 dias ?:</title>
        <option>Enero, diciembre, agosto, junio.</option>
        <option>Febrero, noviembre, octubre, julio.</option>
        <option>Abril, marzo, mayo, septiembre.</option>
        <answer>0</answer>
        <answer>1</answer>
        <answer>2</answer>
    </question>
    <question id="9">
        <type>select</type>
        <title>9. Según la ley de Newton, la fuerza es proporcional a:</title>
        <option>El tiempo</option>
        <option>La velocidad</option>
        <option>La aceleración</option>
        <option>La posición</option> 
        <answer>2</answer>
    </question>
    <question id="10">
        <type>multiple</type>
        <title>10. ¿Qué elementos forman el agua?</title>
        <option>O y H</option>
        <option>Oxígeno e hidrógeno</option>
        <option>Carbono e hidrógeno</option>
        <option>N, O y C</option>
        <answer>0</answer>
        <answer>1</answer>
    </question>	
</questions>